import sys
import json


def get_attribute_sort_key(attribute):
    attribute_name = attribute[0]
    if attribute_name == "id":
        return ""
    elif attribute_name == "category":
        return " "
    else:
        return attribute_name


def get_sort_key_default(item):
    return item["id"]


month_keys = { "jan": "12", "feb": "11", "mar": "10", "apr": "09", "may": "08", "jun": "07", "jul": "06", "aug": "05", "sep": "04", "oct": "03", "nov": "02", "dec": "01" }


def get_sort_key_time(item):
    year_key = 99999 - item["year"]
    month_key = "00"
    if "month" in item:
        month_key = month_keys[item["month"]]
    return f"{year_key} {month_key} {item['id']}"


people_category_order = {
    "Teamlead": "1",
    "Staff": "2",
    "Former Staff": "3"
}


def get_sort_key_people(item):
    return f"{people_category_order[item['category']]} {item['id']}"


def get_sort_key_publications(item):
    year_key = 99999 - item["year"]
    venue = ""
    if "booktitle" in item:
        venue = "A" + item["booktitle"]
    elif "journal" in item:
        venue = "B" + item["journal"]
    elif "school" in item:
        venue = "C" + item["school"]
    return f"{year_key} {month_keys[item['month']]} {venue} {item['id']}"


# Generated by ChatGPT
def dumps_limited(obj, *, max_depth=2, indent=2):
    def _format(o, depth):
        if depth >= max_depth:
            return json.dumps(o, separators=(", ", ": "))

        if isinstance(o, dict):
            items = []
            for k, v in o.items():
                items.append(
                    " " * indent * (depth + 1)
                    + json.dumps(k)
                    + ": "
                    + _format(v, depth + 1)
                )
            return "{\n" + ",\n".join(items) + "\n" + " " * indent * depth + "}"

        if isinstance(o, list):
            items = [
                " " * indent * (depth + 1) + _format(v, depth + 1)
                for v in o
            ]
            return "[\n" + ",\n".join(items) + "\n" + " " * indent * depth + "]"

        return json.dumps(o)

    return _format(obj, 0)


for filename in sys.argv[1:]:
    get_sort_key = get_sort_key_default
    if filename.endswith("data.json"):
        get_sort_key = get_sort_key_time
        print(filename + ": using time sorting")
    elif filename.endswith("events.json"):
        get_sort_key = get_sort_key_time
        print(filename + ": using time sorting")
    elif filename.endswith("people.json"):
        get_sort_key = get_sort_key_people
        print(filename + ": using people sorting")
    elif filename.endswith("publications.json"):
        get_sort_key = get_sort_key_publications
        print(filename + ": using publications sorting")
    elif filename.endswith("downloads-bda-team.json"):
        print(filename + ": skip formatting")
        continue
    else:
        print(filename + ": using default sorting")

    with open(filename) as file:
        data_list = json.load(file)
    data_list = [dict(sorted(item.items(), key=get_attribute_sort_key)) for item in data_list]
    data_list.sort(key=get_sort_key)
    data_json = dumps_limited(data_list) + "\n"
    with open(filename, "w") as file:
        file.write(data_json)

