import sys
import json


def get_attribute_sort_key(attribute):
    attribute_name = attribute[0]
    if attribute_name == "id":
        return ""
    elif attribute_name == "category":
        return " "
    else:
        return attribute_name


def get_sort_key_default(item):
    return item["id"]


event_category_order = {
    "Conferences and Workshops": "1",
    "Invited Talks": "2",
    "Shared Tasks": "3",
    "Teaching": "4"
}


def get_sort_key_events(item):
    yearReverse = 9999 - item["year"]
    return f"{event_category_order[item['category']]} {yearReverse} {item['id']}"


people_category_order = {
    "Teamlead": "1",
    "Staff": "2"
}


def get_sort_key_people(item):
    return f"{people_category_order[item['category']]} {item['id']}"


month_order = { "jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05", "jun": "06", "jul": "07", "aug": "08", "sep": "09", "oct": "10", "nov": "11", "dec": "12" }


def get_sort_key_publications(item):
    venue = ""
    if "booktitle" in item:
        venue = "A" + item["booktitle"]
    elif "journal" in item:
        venue = "B" + item["journal"]
    elif "school" in item:
        venue = "C" + item["school"]
    return f"{item['year']} {month_order[item['month']]} {venue} {item['id']}"


# Generated by ChatGPT
def dumps_limited(obj, *, max_depth=2, indent=2):
    def _format(o, depth):
        if depth >= max_depth:
            return json.dumps(o, separators=(", ", ": "))

        if isinstance(o, dict):
            items = []
            for k, v in o.items():
                items.append(
                    " " * indent * (depth + 1)
                    + json.dumps(k)
                    + ": "
                    + _format(v, depth + 1)
                )
            return "{\n" + ",\n".join(items) + "\n" + " " * indent * depth + "}"

        if isinstance(o, list):
            items = [
                " " * indent * (depth + 1) + _format(v, depth + 1)
                for v in o
            ]
            return "[\n" + ",\n".join(items) + "\n" + " " * indent * depth + "]"

        return json.dumps(o)

    return _format(obj, 0)


for filename in sys.argv[1:]:
    get_sort_key = get_sort_key_default
    reverse = False
    if filename.endswith("events.json"):
        get_sort_key = get_sort_key_events
        print(filename + ": using events sorting")
    elif filename.endswith("people.json"):
        get_sort_key = get_sort_key_people
        print(filename + ": using people sorting")
    elif filename.endswith("publications.json"):
        get_sort_key = get_sort_key_publications
        reverse = True
        print(filename + ": using publications sorting")
    elif filename.endswith("downloads-bda-team.json"):
        print(filename + ": skip formatting")
        continue
    else:
        print(filename + ": using default sorting")

    with open(filename) as file:
        data_list = json.load(file)
    data_list = [dict(sorted(item.items(), key=get_attribute_sort_key)) for item in data_list]
    data_list.sort(key=get_sort_key, reverse=reverse)
    data_json = dumps_limited(data_list) + "\n"
    with open(filename, "w") as file:
        file.write(data_json)

